artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  raw_data_path: artifacts/data_ingestion/raw.csv